title = 'Books Track'
baseURL = 'https://ghassbomb.github.io/books-track'
languageCode = 'en-us'
theme = 'hugo-book'
author = 'Ghassan Shahzad'
description = 'Books Track is a repository of sorts, where I dump plans, notes, exercises, and everything else related to the books I read.'
enableRobotsTXT = true

[params]
  BookTheme = 'light'
  BookToC = true
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true
  BookSection = '*'

[markup.goldmark.renderer] 
unsafe = true

[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/ghassbomb/books-track"
  weight = 10

[[menu.after]]
  name = "My Site"
  url = "https://ghassbomb.github.io/"
  weight = 20