title = 'Books Track'
baseURL = 'https://ghassbomb.github.io/books-track'
languageCode = 'en-us'
theme = 'track-theme'
author = 'Ghassan Shahzad'
description = 'Books Track is a repository of sorts, where I dump plans, notes, exercises, and everything else related to the books I read.'
enableRobotsTXT = true

[params]
github = 'https://github.com/ghassbomb/books-track'
mathjax = false

[markup.goldmark.renderer] 
unsafe = true

[markup]
  [markup.tableOfContents]
    startLevel = 3
    endLevel = 6